Hometask 4
AlexMaximenko/smart-home-2021 pull request #4
Opened 2021-04-07 15:00 UTC by AlexMaximenko

Очень сильно извиняюсь, я забыл сделать pull request когда залил решение (по времени коммита видно, что я залил его до дедлайна) и только сейчас это заметил(

2021-04-09 05:47 UTC, a-ivanov requested changes

2021-04-09 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +        SensorEventsManager eventsManager = new SensorEventsManager();
См гайд, обработчики в отдельных бинах

2021-04-09 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/CCSensorEventAdapter.java
> +public class CCSensorEventAdapter extends CCSensorEvent implements Event {
Зачем в  расширяете ccsensorevent? Я не могу представить ни одного случая, где это будет уместно.

2021-04-09 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/CCSensorEventAdapter.java
> +        libraryEventType = libraryEventType.toUpperCase().replace("IS", "_");
Просто используйте мапу строка на нужный вам тип, ну вот зачем писать столько ненужного сложного кода?

2021-05-06 10:54 UTC, a-ivanov requested changes

2021-05-06 10:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/EventHandlerAdapter.java
> +        this.stringToEventTypeMap.put("LightIsOn", EventType.LIGHT_ON);
Перенесите в бин

2021-05-06 10:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/EventHandlerAdapter.java
> +        EventType type = stringToEventTypeMap.get(event.getEventType());
Проверка на null

2021-05-11 16:09 UTC, AlexMaximenko commented
@a-ivanov

2021-05-11 16:09 UTC, closed without merging